### PR TITLE
Update to 2.088.0 stable release

### PR DESCRIPTION
**Pull request by ghost**
https://dlang.org/changelog/2.088.0.html
https://github.com/dlang/dmd/releases/tag/v2.088.0

### CODE REVIEW

**Comment by joseph-wakeling-frequenz** [comment]
This fails to build for me (using `snapcraft cleanbuild`), falling over when building the `dmd` part:

```
  (HOST_DMD_RUN)  BACK_DOBJS  dmd/backend/elpicpie.d
../generated/host_dmd-2.079.1/dmd2/linux/bin64/dmd -conf=../generated/host_dmd-2.079.1/dmd2/linux/bin64/dmd.conf -c -of../generated/linux/release/64/elpicpie.o  -version=MARS -fPIC -J../generated/linux/release/64 -w -de -O -release -inline -dip25 -m64 -mv=dmd.backend=dmd/backend -betterC -version=DMDV2 dmd/backend/elpicpie.d
../generated/build HOST_DMD="../generated/host_dmd-2.079.1/dmd2/linux/bin64/dmd" OS=linux BUILD=release MODEL=64 AUTO_BOOTSTRAP="1" --called-from-make ../generated/linux/release/64/lexer.a
../generated/build HOST_DMD="../generated/host_dmd-2.079.1/dmd2/linux/bin64/dmd" OS=linux BUILD=release MODEL=64 AUTO_BOOTSTRAP="1" --called-from-make -f ../generated/linux/release/64/VERSION
../generated/build HOST_DMD="../generated/host_dmd-2.079.1/dmd2/linux/bin64/dmd" OS=linux BUILD=release MODEL=64 AUTO_BOOTSTRAP="1" --called-from-make ../generated/linux/release/64/SYSCONFDIR.imp
Using Bootstrap compiler: 2.079.1
Downloading DMD 2.079.1
Using Bootstrap compiler: 2.079.1
Downloading DMD 2.079.1
Using Bootstrap compiler: 2.079.1
Downloading DMD 2.079.1
(TX) VERSION
Success
(TX) SYSCONFDIR
Success
(DC) D_LEXER_OBJ console.d, entity.d, errors.d, filecache.d, globals.d, id.d, identifier.d, lexer.d, tokens.d, utf.d, array.d, ctfloat.d, file.d, filename.d, hash.d, outbuffer.d, port.d, rmem.d, rootobject.d, stringtable.d
Error: unrecognized switch '-flto=full'
       run 'dmd -man' to open browser on manual

posix.mak:613: recipe for target '../generated/linux/release/64/lexer.a' failed
make[1]: *** [../generated/linux/release/64/lexer.a] Error 1
make[1]: Leaving directory '/root/build_dmd/parts/dmd/build/src'
posix.mak:8: recipe for target 'all' failed
make: *** [all] Error 2
Sorry, an error occurred in Snapcraft:
Failed to run 'make -f posix.mak AUTO_BOOTSTRAP=1 ENABLE_RELEASE=1 ENABLE_LTO=1 -j24' for 'dmd': Exited with code 2.
Verify that the part is using the correct parameters and try again.
```

**Comment by ghost** [comment]
uhm this is weird, we have to ask

**Comment by WebDrake** [comment]
Did you get any insight into what's going wrong?

**Comment by ghost** [comment]
ENABLE_LTO is not currently supported with the new build.d (in the last release they have moved the generation of many obj into build.d), for now we need to disable LTO optimization

**Comment by joseph-wakeling-frequenz** [comment]
Can you note the reason for removing it in the commit message?  Other than that LGTM :-)

**Comment by ghost** [comment]
Ok done

**Comment by joseph-wakeling-frequenz** [comment]
LGTM, feel free to take in at your convenience.  Do we have a 2.088 release channel or do we need to request it?

**Comment by ghost** [comment]
I have just sent the request

**Pull request merged**
